<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensaje1 [
    <!ELEMENT mensaje1 (remitente, destinatario, asunto, contenido)>
    <!ELEMENT remitente (#PCDATA)>
    <!ELEMENT destinatario (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>
]>
<mensaje1>
  <remitente>fulanico@gmail.com</remitente>
  <destinatario>menganico@gmail.com</destinatario>
  <asunto>Bar de Paco</asunto>
  <contenido>Quedamos a las 4 pa un cafe o que???</contenido>
</mensaje1>