<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personajes [
	<!ELEMENT personajes (personaje*)>
	<!ELEMENT personaje (nombre, nacionalidad?, altura, peso?, grupo_sanguineo?, datos_personales*)>
	<!ELEMENT nombre (#PCDATA)>
	<!ELEMENT nacionalidad (#PCDATA)>
	<!ELEMENT altura (#PCDATA)>
	<!ELEMENT peso (#PCDATA)>
	<!ELEMENT grupo_sanguineo (#PCDATA)>
	<!ELEMENT datos_personales (aficion*, aversion*)>
	<!ELEMENT aficion (#PCDATA)>
	<!ELEMENT aversion (#PCDATA)>
]>
<personajes>
	<personaje>
		<nombre>Balrog</nombre>
		<nacionalidad>EEUU</nacionalidad>
		<altura>193</altura>
		<peso>135</peso>
		<grupo_sanguineo>A</grupo_sanguineo>
		<datos_personales>
			<aficion>bourbon</aficion>
			<aficion>dinero</aficion>
			<aversion>pescado</aversion>
			<aversion>matemáticas</aversion>
		</datos_personales>
	</personaje>
	<personaje>
		<nombre>M. Bison</nombre>
		<nacionalidad/>
		<altura>180</altura>
		<peso>80</peso>
		<grupo_sanguineo></grupo_sanguineo>
		<datos_personales>
			<aficion>dominar el mundo</aficion>
			<aversion>la música pop</aversion>
			<aversion>desobediencia</aversion>
		</datos_personales>
	</personaje>
	<personaje>
		<nombre>Chun-Li</nombre>
		<nacionalidad>China</nacionalidad>
		<altura>173</altura>
		<peso/>
		<grupo_sanguineo>A</grupo_sanguineo>
		<datos_personales>
			<aficion>Su padre</aficion>
			<aficion>Crepres</aficion>
			<aficion>yogashi</aficion>
		</datos_personales>
	</personaje>
	<personaje>
		<nombre>Dhalsim</nombre>
		<nacionalidad>India</nacionalidad>
		<altura>176</altura>
		<peso>70</peso>
		<grupo_sanguineo>O</grupo_sanguineo>
		<datos_personales/>
	</personaje>
</personajes>